# Generated by Django 2.2.5 on 2020-06-12 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='reports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filepath', models.FileField(null=True, upload_to='reports/', verbose_name='')),
                ('collection_drive_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.collection_drive')),
                ('donation_drive_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.donation_drive')),
            ],
        ),
    ]
