# Generated by Django 2.2.5 on 2020-06-10 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='file',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.collection_drive')),
                ('donation_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.donation_drive')),
            ],
            options={
                'db_table': 'file',
            },
        ),
    ]
