# Generated by Django 2.2.5 on 2020-06-13 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='dstock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dquantity', models.IntegerField()),
                ('dcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.stock')),
            ],
            options={
                'db_table': 'dstock',
            },
        ),
    ]
