# Generated by Django 2.2.5 on 2020-06-12 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200612_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reports',
            name='filepath',
            field=models.FileField(null=True, upload_to='files/', verbose_name=''),
        ),
        migrations.AlterModelTable(
            name='reports',
            table='reports',
        ),
    ]
