# Generated by Django 2.2.5 on 2020-06-13 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200613_1556'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reports',
            unique_together={('donation_drive_date', 'collection_drive_date')},
        ),
    ]
