# Generated by Django 2.2.5 on 2020-06-13 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200613_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reports',
            name='collection_drive_date',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.collection_drive'),
        ),
        migrations.AlterField(
            model_name='reports',
            name='donation_drive_date',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.donation_drive'),
        ),
        migrations.AlterUniqueTogether(
            name='reports',
            unique_together=set(),
        ),
    ]
